# This is a basic workflow that is manually triggered

name: update euro-cordex simulation list

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - "*"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: update tables
      env:
        WANDB_CONSOLE: "off"
      run: |
        python access-esgf.py

    - name: Check if there are any changes in the table
      id: verify_diff
      run: |
        git diff euro-cordex-esgf.csv --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        #(pre-commit run --all-files) || true
        git commit euro-cordex-esgf.csv -m "update table"
        git status
        git push
